-- MySQL Script generated by MySQL Workbench
-- Fri Aug 12 08:11:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aia_logistics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aia_logistics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aia_logistics` DEFAULT CHARACTER SET utf8mb4 ;
USE `aia_logistics` ;

-- -----------------------------------------------------
-- Table `aia_logistics`.`gudang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aia_logistics`.`gudang` ;

CREATE TABLE IF NOT EXISTS `aia_logistics`.`gudang` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_admin` INT(10) UNSIGNED NULL DEFAULT NULL,
  `nama` VARCHAR(64) NOT NULL,
  `alamat` VARCHAR(255) NOT NULL,
  `id_kode_kota` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_admin` (`id_admin` ASC) VISIBLE,
  INDEX `id_kode_kota` (`id_kode_kota` ASC) VISIBLE,
  CONSTRAINT `gudang_ibfk_371`
    FOREIGN KEY (`id_admin`)
    REFERENCES `aia_logistics`.`users` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `gudang_ibfk_372`
    FOREIGN KEY (`id_kode_kota`)
    REFERENCES `aia_logistics`.`kode_kota` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aia_logistics`.`kode_kota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aia_logistics`.`kode_kota` ;

CREATE TABLE IF NOT EXISTS `aia_logistics`.`kode_kota` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `kode` VARCHAR(64) NOT NULL,
  `nama` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `kode_kota_kode` (`kode` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aia_logistics`.`ongkir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aia_logistics`.`ongkir` ;

CREATE TABLE IF NOT EXISTS `aia_logistics`.`ongkir` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `kota_pengirim` VARCHAR(64) NOT NULL,
  `kota_penerima` VARCHAR(64) NOT NULL,
  `ongkir` INT(10) UNSIGNED NOT NULL,
  `kode` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `kota_pengirim` (`kota_pengirim` ASC) VISIBLE,
  INDEX `kota_penerima` (`kota_penerima` ASC) VISIBLE,
  INDEX `kode` (`kode` ASC) VISIBLE,
  CONSTRAINT `ongkir_ibfk_436`
    FOREIGN KEY (`kota_pengirim`)
    REFERENCES `aia_logistics`.`kode_kota` (`kode`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `ongkir_ibfk_437`
    FOREIGN KEY (`kota_penerima`)
    REFERENCES `aia_logistics`.`kode_kota` (`kode`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `ongkir_ibfk_438`
    FOREIGN KEY (`kode`)
    REFERENCES `aia_logistics`.`kode_kota` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aia_logistics`.`pengiriman`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aia_logistics`.`pengiriman` ;

CREATE TABLE IF NOT EXISTS `aia_logistics`.`pengiriman` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pesanan` VARCHAR(64) NOT NULL,
  `id_gudang` INT(10) UNSIGNED NOT NULL,
  `keterangan` VARCHAR(255) NOT NULL,
  `waktu` DATETIME NOT NULL,
  `id_kurir` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pesanan` (`id_pesanan` ASC) VISIBLE,
  INDEX `id_gudang` (`id_gudang` ASC) VISIBLE,
  INDEX `id_kurir` (`id_kurir` ASC) VISIBLE,
  CONSTRAINT `pengiriman_ibfk_518`
    FOREIGN KEY (`id_pesanan`)
    REFERENCES `aia_logistics`.`pesanan` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `pengiriman_ibfk_519`
    FOREIGN KEY (`id_gudang`)
    REFERENCES `aia_logistics`.`gudang` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `pengiriman_ibfk_520`
    FOREIGN KEY (`id_kurir`)
    REFERENCES `aia_logistics`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aia_logistics`.`pesanan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aia_logistics`.`pesanan` ;

CREATE TABLE IF NOT EXISTS `aia_logistics`.`pesanan` (
  `id` VARCHAR(64) NOT NULL,
  `id_admin` INT(10) UNSIGNED NOT NULL,
  `resi` VARCHAR(64) NOT NULL,
  `nama_barang` VARCHAR(64) NOT NULL,
  `nama_pengirim` VARCHAR(64) NOT NULL,
  `nama_penerima` VARCHAR(64) NOT NULL,
  `alamat_pengirim` VARCHAR(255) NOT NULL,
  `alamat_penerima` VARCHAR(255) NOT NULL,
  `no_hp_pengirim` VARCHAR(64) NOT NULL,
  `no_hp_penerima` VARCHAR(64) NOT NULL,
  `berat` INT(10) UNSIGNED NOT NULL,
  `ongkir` INT(10) UNSIGNED NOT NULL,
  `status` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pesanan_resi` (`resi` ASC) VISIBLE,
  INDEX `id_admin` (`id_admin` ASC) VISIBLE,
  CONSTRAINT `pesanan_ibfk_1`
    FOREIGN KEY (`id_admin`)
    REFERENCES `aia_logistics`.`users` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aia_logistics`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aia_logistics`.`roles` ;

CREATE TABLE IF NOT EXISTS `aia_logistics`.`roles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_role` (`role` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aia_logistics`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aia_logistics`.`users` ;

CREATE TABLE IF NOT EXISTS `aia_logistics`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `password` TEXT NOT NULL,
  `no_hp` VARCHAR(64) NOT NULL,
  `id_role` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email` (`email` ASC) VISIBLE,
  INDEX `id_role` (`id_role` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`id_role`)
    REFERENCES `aia_logistics`.`roles` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
